<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>ThoNohT.NohBoard.Hooking</RootNamespace>
    <AssemblyName>NohBoard.Hooking</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyTitle>NohBoard.Hooking</AssemblyTitle>
    <Product>NohBoard Hooking Library</Product>
    <Description>A keyboard and mouse hooking library for NohBoard</Description>
    <Company>ThoNohT</Company>
    <Copyright>Copyright © 2016</Copyright>
  </PropertyGroup>

</Project>
